### ISSUE TITLE
您好  小白请教几个问题

### ISSUE THREAD

**Issue by insurgentZhao** [12207480/TYDownloadManager#10]
我的页面上有一个下载视频的按钮  点击下载视频以后  要到个人中心的->  我的缓存界面查看  怎么才能实时更新这些数据   TYDownloadManager只提供了这两个属性来实时观察。 怎么才能把暂停的数据  和已完成的数据  同时显示出来  并且不会丢失  谢谢您。
@property (nonatomic, strong) NSMutableArray *waitingDownloadModels;
// 等待中的模型
@property (nonatomic, strong) NSMutableArray *downloadingModels;

**Comment by ycace** [comment]
其实你可以在目前的基础上再封装一层 比如记录你的下载记录以及进度状态之类 放到数据库或者plist表中去实现自己更多的需求。这件事情比较简单 给你一个思路 我也是前一段时间看到这个库不错就做了封装拿到项目中去用了
