### ISSUE TITLE
TYDownLoadDataManager 与 TYDownloadSessionManager的区别

### ISSUE THREAD

**Issue by GitterYang** [12207480/TYDownloadManager#11]
请问，TYDownLoadDataManager 与 TYDownloadSessionManager  这2个有什么区别？

**Comment by 12207480** [comment]
TYDownloadSessionManager支持后台下载

**Comment by GitterYang** [comment]
使用TYDownloadSessionManager下载的时候，如果其中一个任务暂停了，就找不到那个任务了。waitingDownloadModels和downloadingModels只代表下载中的任务，对于做列表不好展示

**Comment by 12207480** [comment]
![image](https://cloud.githubusercontent.com/assets/6346030/19670862/4a175bdc-9a9d-11e6-8045-8fa274508d3a.png)
通过url获取是否包含model 了

**Comment by GitterYang** [comment]
比如说我有一个下载列表，包含下载中和已下载的，请问怎么能取到对应的数据源？下载中应该包括waitingDownloadModels，downloadingModels以及暂停Models，但是现在怎么才能一下全部取到所有的暂停Models呢?麻烦提供下思路

**Comment by 12207480** [comment]
这个需要你自己 保存一个数组 包含已下载和正在下载数据
