### ISSUE TITLE
TYDownloadSessionManager后台下载问题

### ISSUE THREAD

**Issue by guyuliunian** [12207480/TYDownloadManager#41]
用TYDownloadSessionManager可以禁用后台下载吗？我在AppDelegate中没有设置后台下载设置，结果还是能进行后台下载，这个问题能帮忙解决下吗？

**Comment by guyuliunian** [comment]
换用TYDownloadDataManager可以了，发现在真机上如果我一直是wifi状态，退到后台，立即返回app，会发现下载还在进行，如果停留时间过长，就直接下载失败，如果在WiFi状态下退到后台，然后切换网络到4G，回到前台，是暂停的。而如果在模拟器上，后台也是能下载的，不知道这个大神有没有遇到过？而TYDownloadSessionManager无论怎么样操作，发现在后台都是能下载的，前提是我没有配置过后台下载，还是说这个类本身就支持后台下载，如果不想在后台下载只能用TYDownloadDataManager是吗？

**Comment by 12207480** [comment]
这个类本身就支持后台下载,
在进入后台cancle
在进入前台start

**Comment by guyuliunian** [comment]
哦哦，多谢解答。我以为是不配置就不会进行后台下载的，看来我理解错了，也就是如果想用sessionManager实现，只能在进入后台和进入前台的时候手动控制
