### ISSUE TITLE
同时下载多个总会闪退~~~ 复现频率蛮高的 ios9系统环境，不确定其他环境。

### ISSUE THREAD

**Issue by hydyy** [12207480/TYDownloadManager#6]
2016-09-07 13:45:16.115 EdujiaAppd[13902:2313195] Bugly:  Trapped uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter' 
(
	0   CoreFoundation                      0x000000010f3cfd85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x00000001139bcdeb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010f3cfcbd +[NSException raise:format:] + 205
	3   Foundation                          0x0000000110146157 -[NSURL(NSURL) initFileURLWithPath:] + 131
	4   Foundation                          0x00000001101460bf +[NSURL(NSURL) fileURLWithPath:] + 45
	5   EdujiaAppd                          0x000000010ce71ccb -[TYDownloadSessionManager moveFileAtURL:toPath:] + 539
	6   EdujiaAppd                          0x000000010ce72afd -[TYDownloadSessionManager URLSession:downloadTask:didFinishDownloadingToURL:] + 637
	7   CFNetwork                           0x000000010ef08cca __82-[NSURLSession delegate_downloadTask:didFinishDownloadingToURL:completionHandler:]_block_invoke + 38
	8   Foundation                          0x0000000110212630 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	9   Foundation                          0x000000011014d805 -[NSBlockOperation main] + 101
	10  Foundation                          0x0000000110130725 -[__NSOperationInternal _start:] + 646
	11  Foundation                          0x0000000110130336 __NSOQSchedule_f + 194
	12  libdispatch.dylib                   0x0000000114b443eb _dispatch_client_callout + 8
	13  libdispatch.dylib                   0x0000000114b2a82c _dispatch_queue_drain + 2215
	14  libdispatch.dylib                   0x0000000114b29d4d _dispatch_queue_invoke + 601
	15  libdispatch.dylib                   0x0000000114b2c996 _dispatch_root_queue_drain + 1420
	16  libdispatch.dylib                   0x0000000114b2c405 _dispatch_worker_thread3 + 111
	17  libsystem_pthread.dylib             0x0000000114e814de _pthread_wqthread + 1129
	18  libsystem_pthread.dylib             0x0000000114e7f341 start_wqthread + 13
)

**Comment by hydyy** [comment]
刚跟了一下发现是通过block去获取保存地址了， 结果我block没实现，返回地址为空造成的。 那这个block就是必须的呀， 是否应该readme写出来，不然我不跟是不会知道需要实现这个block的
backgroundSessionDownloadCompleteBlock

**Comment by 12207480** [comment]
恩 我看下

**Comment by 12207480** [comment]
是你没设置filepath吧
