### ISSUE TITLE
你好 有一个 小问题

### ISSUE THREAD

**Issue by LittleVoyager** [12207480/TYDownloadManager#7]
// 下载中的模型 只读
@property (nonatomic, strong,readonly) NSMutableArray *waitingDownloadModels;

// 等待中的模型 只读
@property (nonatomic, strong,readonly) NSMutableArray *downloadingModels;

你的命名 和 注释 不知道是不是写反了。。

**Comment by 12207480** [comment]
恩 是的 谢谢
