### ISSUE TITLE
崩溃问题

### ISSUE THREAD

**Issue by LittleVoyager** [12207480/TYDownloadManager#8]
libBacktraceRecording.dylib`__gcd_queue_item_enqueue_hook_block_invoke:
    0x10cd9eea8 <+0>:  pushq  %rbp
    0x10cd9eea9 <+1>:  movq   %rsp, %rbp
->  0x10cd9eeac <+4>:  movq   0x20(%rsi), %rax
    0x10cd9eeb0 <+8>:  movq   0x20(%rdi), %rcx
    0x10cd9eeb4 <+12>: cmpq   0x8(%rcx), %rax
    0x10cd9eeb8 <+16>: sete   %al
    0x10cd9eebb <+19>: popq   %rbp
    0x10cd9eebc <+20>: retq   

xcode 8   iOS 10模拟器 偶尔崩溃

**Comment by 12207480** [comment]
这个看不出来也 没有更详细的吗
